plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.yarukov'
version = property('appVersion')
description = 'backend'

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.annotationProcessorPath = configurations.annotationProcessor
}


sourceSets {
    functionalTest {
        java.srcDir 'src/functionalTest/java'
    }
}

configurations {
    functionalTestImplementation.extendsFrom testImplementation
    functionalTestRuntimeOnly.extendsFrom testRuntimeOnly
}




repositories {
    mavenCentral()
}


dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-jooq'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testCompileOnly 'org.projectlombok:lombok:1.18.34'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'
    testImplementation 'com.microsoft.playwright:playwright:1.49.0'

}

tasks.register('myCompile', JavaCompile) {
    group = 'opi'
    description = 'compilation'
    source = fileTree('src/main/java')
    destinationDirectory = file('build/classes/java/main')
    classpath = configurations.compileClasspath
    options.encoding = 'UTF-8'
    options.annotationProcessorPath = configurations.annotationProcessor
}


tasks.named('bootJar') {
    archiveBaseName = project.property('appArchiveName')
    archiveVersion = project.property('appVersion')

    classpath = files(tasks.named('myCompile'), configurations.runtimeClasspath)

    from('src/main/resources') {
        into('BOOT-INF/classes')
    }

    manifest {
        attributes(
                'Start-Class': project.property('mainClass'),
                'Implementation-Version': project.property('appVersion')
        )
    }
}


tasks.register('myBuild') {
    group = 'opi'
    description = 'build'
    inputs.files(tasks.named('functionalTest'))
    inputs.files(tasks.named('bootJar'))
    outputs.files(tasks.named('bootJar'))
}


tasks.register('myClean') {
    group = 'opi'
    description = 'clean'
    doLast {
        def buildDir = file('build')
        if (buildDir.exists()) {
            buildDir.deleteDir()
        } else {
            println "not found buld dir"
        }
    }
}


tasks.register("native2ascii") {
    group = 'opi'
    description = 'convertion to ascii'
    def srcDir = file(providers.gradleProperty('localizationSrcDir').getOrElse('src/main/resources/localization'))
    inputs.dir(srcDir)
    def outDir = file(providers.gradleProperty('localizationOutDir').getOrElse('build/generated-resources/ascii-locales'))
    outputs.dir(outDir)
    doLast {
        inputs.files.each { File inputFile ->
            def outputFile = new File(outDir, srcDir.toPath().relativize(inputFile.toPath()).toString())
            outputFile.parentFile.mkdirs()

            def convertedContent = inputFile.getText('UTF-8').toCharArray().collect { char c ->
                (c > 127) ? String.format("\\u%04x", (c as int)) : c
            }.join("")
            outputFile.write(convertedContent, "ISO-8859-1")
        }
    }
}


tasks.register("diff") {
    group = 'opi'
    description = "check and copy classes in properties"
    doLast {
        def workingDir = project.projectDir
        def repoRoot = "git rev-parse --show-toplevel".execute(null, workingDir).text.trim()
        def currentDir = workingDir.absolutePath.replace("\\", "/")
        def prefix = currentDir.replace(repoRoot.replace("\\", "/"), "").replaceFirst("^/", "") + "/"
        def gitNeedComm = project.property("diffClasses").split(",")
        def gitStatus = "git status --porcelain".execute().text
        def changedFiles = []
        gitStatus.eachLine {
            line ->
                if (line.contains('backend')) {
                    def lineStr = line.split('/')
                    def lineSubstr = line.substring(3)
                    def lastPathToFIle = lineStr[-1]
                    if (gitNeedComm.contains(lastPathToFIle)) {
                        changedFiles.add(lineSubstr.replace(prefix, ""))
                    }
                }
        }
        println changedFiles
        if (!changedFiles.isEmpty()) {

            changedFiles.each { file -> "git add ${file}".execute(null, workingDir).waitFor() }
            def msg = project.property('diffCommitMessage')
            def commitProcess = "git commit -m \"${msg}\"".execute(null, workingDir)
            commitProcess.waitFor()
            if (commitProcess.exitValue() == 0) {
                println "Success commit"
            } else {
                def errorText = commitProcess.err.text
                print errorText
            }
        } else {
            println "No changes"
        }
    }
}




tasks.register('myTest',Test) {
    group = 'opi'
    description = 'unit-test'
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    useJUnitPlatform()
    jvmArgs '-XX:+EnableDynamicAgentLoading'
    testLogging {
        events "passed", "skipped", "failed"
    }
}



tasks.register('functionalTest', Test) {
    group = 'opi'
    description = 'functional tests'

    testClassesDirs = sourceSets.functionalTest.output.classesDirs
    classpath = sourceSets.functionalTest.runtimeClasspath

    useJUnitPlatform()
    jvmArgs '-XX:+EnableDynamicAgentLoading','-Dfile.encoding=UTF-8', '-Dsun.stdout.encoding=UTF-8'

    outputs.upToDateWhen { false }

    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
    }
}

tasks.register('dockerModulTests', Exec) {
    group = 'docker'
    description = 'isolation modul tests'
    dependsOn 'myBuild'
    commandLine 'docker', 'run', '--rm',
            '-v', "${project.projectDir.absolutePath}:/app",
            '-v', '/app/.gradle',
            '-v', '/app/build',
            '-w', '/app',
            'eclipse-temurin:21-jdk-alpine',
            './gradlew', 'myTest', '--no-daemon'
}

tasks.register('dockerTestUp', Exec) {
    group = 'docker'
    description = 'up docker tests'
    dependsOn 'myBuild'
    workingDir = project.projectDir.parentFile
    commandLine 'docker', 'compose', '-f', 'docker-compose.test.yaml', 'up', '-d', '--build'
}


tasks.register('dockerTestDown', Exec) {
    group = 'docker'
    description = 'down docker tests'
    workingDir = project.projectDir.parentFile
    commandLine 'docker', 'compose', '-f', 'docker-compose.test.yaml', 'down', '-v'
}

tasks.register('dockerFunctionalTest', Exec) {
    group = 'docker'
    description = 'isolation funtional tests'
    dependsOn 'dockerTestUp'
    workingDir = project.projectDir
    commandLine 'docker', 'run', '--rm',
            '--network', 'host',
            '-v', "${project.projectDir.absolutePath}:/app",
            '-v', '/app/.gradle',
            '-v', '/app/build',
            '-w', '/app',
            'mcr.microsoft.com/playwright/java:v1.49.0-noble',
            './gradlew', 'functionalTest', '--no-daemon'

    finalizedBy 'dockerTestDown'
}



tasks.register('buildRevisions') {
    group = 'opi'
    description = 'Сборка нескольких коммитов/ревизий из Git в Docker'

    doLast {
        def revisions = project.hasProperty('revisions')
                ? project.property('revisions').toString().split(',')*.trim()
                : ['HEAD','HEAD~1']
        def execOps = services.get(ExecOperations)
        def stdout = new ByteArrayOutputStream()
        execOps.exec {
            commandLine = ['git', 'rev-parse', '--abbrev-ref', 'HEAD',]
            standardOutput = stdout
        }
        def currentBranch = stdout.toString().trim()
        if (currentBranch.isEmpty() || currentBranch == "HEAD") {
            stdout.reset()
            execOps.exec {
                commandLine = ['git', 'rev-parse', 'HEAD']
                standardOutput = stdout
            }
            currentBranch = stdout.toString().trim()
        }

        revisions.each { rev ->
            execOps.exec {
                commandLine = ['git', 'checkout', rev]
            }
            stdout.reset()
            execOps.exec {
                commandLine = ['git', 'rev-parse', '--short', 'HEAD']
                standardOutput = stdout
            }
            def commitHash = stdout.toString().trim()
            execOps.exec {
                workingDir = project.projectDir
                commandLine = ['docker', 'build', '-t', "web4-backend:${commitHash}", '.']
            }
            println "web4-backend:${commitHash} created"
        }


        execOps.exec {
            commandLine = ['git', 'checkout', currentBranch]
        }
        println "alll revisions build"
    }
}

















