org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8
appVersion=1.0.0
mainClass=com.yarukov.backend.BackendApplication
localizationSrcDir=src/main/resources/localization
localizationOutputDir=build/generated-resources/ascii-locales
diffClasses=PointService.java,AuthService.java,Point.java,PointController.java,AuthController.java
diffCommitMessage=monitored classes were modified
appArchiveName=web4-backend
